CREATE TABLE IF NOT EXISTS products (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  scent TEXT NULL,
  description LONGTEXT NULL,
  price INT NOT NULL DEFAULT 0,
  image VARCHAR(255) NULL,
  video VARCHAR(255) NULL,
  badge VARCHAR(255) NULL,
  out_of_stock TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
